### ISSUE TITLE
NPE on IDEA startup

### ISSUE THREAD

**Issue by 3rwww1** [MCMicS/jenkins-control-plugin#93]
Using Jenkins Jenkins ver. 1.609.1 and latest IDEA, the plugin fails at startup with a NullPointerException.

My server is configured to serve content directly from the root of the webserver (e.g. it's http://jenkins.myurl.com/, not http://myurl.com/jenkins). I get an "EmptyJSON" when I try to access a resource inside this address (e.g http://jenkins.myurl.com/users)

I tried both unauthenticated and authenticated access, to no avail. The plugin configuration reports everything is OK.

Here are the stacktrace and message:

```
null
```

```
java.lang.NullPointerException
    at org.codinjutsu.tools.jenkins.logic.JenkinsJsonParser.getJob(JenkinsJsonParser.java:175)
    at org.codinjutsu.tools.jenkins.logic.JenkinsJsonParser.createViewJobs(JenkinsJsonParser.java:296)
    at org.codinjutsu.tools.jenkins.logic.RequestManager.loadJenkinsView(RequestManager.java:108)
    at org.codinjutsu.tools.jenkins.view.BrowserPanel.loadJobs(BrowserPanel.java:412)
    at org.codinjutsu.tools.jenkins.view.BrowserPanel.access$400(BrowserPanel.java:67)
    at org.codinjutsu.tools.jenkins.view.BrowserPanel$LoadSelectedViewJob.run(BrowserPanel.java:511)
    at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:563)
    at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:152)
    at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:452)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:402)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
    at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:137)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl$1.run(ProgressManagerImpl.java:126)
    at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:400)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
    at org.jetbrains.ide.PooledThreadExecutor$1$1.run(PooledThreadExecutor.java:56)
```

**Comment by dboissier** [comment]
Hi,

The plugin has been fixed by @cezary-butler. It is deployed on jetbrains repository and may fix the issue you encounter

**Comment by nickgrealy** [comment]
Hi @dboissier (@cezary-butler),

First of all, thanks for the plugin!

Can you please link the commit/pull request/fix to this issue? I can't reconcile the fix with the current version of the plugin (i.e. I'm still getting this issue with v0.9.4 of the plugin - see #107 ). Happy to help with details to reproduce the issue.

Also, the open issues linked to this ticket can probably be closed as "duplicates".

Kind regards,
Nick

**Comment by dboissier** [comment]
Hi,

I should release a version by this end of this week. Hope it will fix the bug you encountered.

**Comment by MCMicS** [comment]
If error still occurs with 0.11.0 please feel free to reopen.
